-- Sustainers NEST - NEW SUPABASE PROJECT
-- STEP 1 OF 3: CREATE DATABASE TABLES

create extension if not exists pgcrypto;

create table public.contact_submissions (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text not null,
  topic text not null,
  message text not null,
  source_path text,
  status text not null default 'new',
  created_at timestamptz not null default now()
);

create table public.volunteer_applications (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text not null,
  area_of_interest text not null,
  about text,
  source_path text,
  status text not null default 'new',
  created_at timestamptz not null default now()
);

create table public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  email text not null,
  role text not null default 'editor',
  active boolean not null default true,
  must_change_password boolean not null default false,
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index admin_users_email_lower_uidx
  on public.admin_users (lower(email));

create table public.admin_audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  actor_email text,
  action text not null,
  resource_type text not null,
  resource_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table public.activities (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  project_key text not null,
  project_label text not null,
  title text not null,
  institute text,
  date_label text not null default '',
  start_date date,
  end_date date,
  sort_date date not null,
  description text not null default '',
  thumbnail_url text,
  detail_url text,
  status_label text not null default 'Completed',
  featured_home boolean not null default false,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.activity_photos (
  id uuid primary key default gen_random_uuid(),
  activity_id uuid not null references public.activities(id) on delete cascade,
  image_url text not null,
  alt_text text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table public.team_members (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  team_group text not null,
  name text not null,
  role_title text not null,
  motto text,
  photo_url text,
  photo_position text not null default 'center 25%',
  sort_order integer not null default 100,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.impact_metrics (
  metric_key text primary key,
  label text not null,
  value_number integer not null default 0,
  suffix text not null default '',
  sort_order integer not null default 100,
  published boolean not null default true,
  updated_at timestamptz not null default now()
);

create table public.site_settings (
  setting_key text primary key,
  value jsonb not null default '{}'::jsonb,
  is_public boolean not null default false,
  updated_at timestamptz not null default now()
);

create table public.gallery_items (
  id uuid primary key default gen_random_uuid(),
  image_url text not null,
  caption text,
  activity_id uuid references public.activities(id) on delete set null,
  project_key text,
  sort_order integer not null default 100,
  published boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.partners (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  website_url text,
  logo_url text,
  description text,
  sort_order integer not null default 100,
  published boolean not null default true,
  created_at timestamptz not null default now()
);

create index contact_submissions_created_at_idx
  on public.contact_submissions (created_at desc);

create index volunteer_applications_created_at_idx
  on public.volunteer_applications (created_at desc);

create index admin_audit_log_created_at_idx
  on public.admin_audit_log (created_at desc);

create index activities_sort_date_idx
  on public.activities (sort_date desc);

create index activities_project_idx
  on public.activities (project_key, sort_date desc);

create index activity_photos_activity_idx
  on public.activity_photos (activity_id, sort_order);

create index team_members_group_idx
  on public.team_members (team_group, published, sort_order);

select table_name
from information_schema.tables
where table_schema = 'public'
  and table_name in (
    'contact_submissions',
    'volunteer_applications',
    'admin_users',
    'admin_audit_log',
    'activities',
    'activity_photos',
    'team_members',
    'impact_metrics',
    'site_settings',
    'gallery_items',
    'partners'
  )
order by table_name;
